name: Build WASM4 Cart

on:
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
  
      - name: Install wasm4
        run: npm install -g wasm4 
  
      - name: Set wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Build
        run: cargo build --verbose

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Run rustfmt
        run: cargo fmt

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: apply rustfmt" 


