name: Build WASM4 Cart

on:
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
  
      - name: Install wasm4
        run: npm install -g wasm4 
  
      - name: Install wasm4-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown
  
      - name: Build
        run: cargo build --verbose